### PR TITLE
Maximum Commit Date

### PR DESCRIPTION
**Pull request by lloydChris**
When a Vault Repo is very old, the very old changes may not be relevant and this filter attempts to save time by reducing the number of commits that have to be converted.

### CODE REVIEW

**Comment by robe070** [comment]
Good idea, though we always grab all history. We ran it on a fast AWS instance to start with for the initial conversion so it didn't take so long. I'd merge it except that you've updated the DLLs and changed more in appconfig than just the new property.

**Comment by lloydChris** [comment]
There is a commit in this PR that reverts my additional app.config changes, so I am seeing just the new property `OldestCommitDate` being added.  The DLLs are updated to use Version 9 vault which we needed to match our server.

**Review by robe070 — CHANGES_REQUESTED** [review]
The DLLs are specific to each environment. They should not be in a PR. I won't be able to merge the PR if they are left in.

**Review by robe070 — COMMENTED** [review]
I'm a newbie at pull requests. Now I've viewed all the commits as 1 I can see app.config is correct.

**Comment by lloydChris** [comment]
> The DLLs are specific to each environment. They should not be in a PR. I won't be able to merge the PR if they are left in.

I agree that DLLs should not be in source control at all.  However, they are already in the project (https://github.com/robe070/vault2git2/tree/master/Vault2GitLib/libs/VaultClientAPI_5_0_3_18802), I am just adding a newer version.  These DLLs are not ones that I have compiled on my machine, but are provided by SourceGear.  Ideally they would be managed by Nuget or similar.  I have relocated the ones I added to be in their own version specific folder to conform with the existing convention.

**Comment by robe070** [comment]
@lloydChris You backed out my end date change that I just made. The one that allowed the convertor to work from the 1st Jan. Rather than go through another loop I've merged your PR and then applied the fix again. Its in master if you want it still to work for you.

**Comment by lloydChris** [comment]
Apologies, a careless rebase on my part.

Thanks for the merge!

**Pull request merged**
